apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jenkins
  description: An example of a Backstage application.
  annotations:
    jenkins.io/job-full-name: java
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  #type: website
  type: service
  #owner: john@example.com
  owner: guests
  lifecycle: experimental
